# Generated by Django 4.2.1 on 2023-05-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='normal',
            field=models.IntegerField(choices=[(1, 'credit'), (-1, 'debit')]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.IntegerField(choices=[(1, 'credit'), (-1, 'debit')]),
        ),
    ]
